### ISSUE TITLE
Exclusion of articles by section does not work

### ISSUE THREAD

**Issue by astick360** [gocom/rah_sitemap#11]
I enter the following data into the field: Exclude articles based on fields (field: value, comma-separated). However, there are articles from these sections still visible in the sitemap.

The inputs are: Section: demo1, Section: demo2, Section: demo3, Section: demo4, Section: demo5

The CMS version is: 4.9, I don't know if this is the reason, but I need to make a project on this version.
Is there a chance to verify and possibly repair?

**Comment by gocom** [comment]
Thank you for the report @astick360.

This appears to be regression in the rah_sitemap version 3.0.0, where it no longer is able to filter by the custom column mapping expression. I'll fix it.

**Comment by gocom** [comment]
rah_sitemap version 4.0.2 is now available, which fixes this issue:
https://github.com/gocom/rah_sitemap/releases/tag/4.0.2
