### ISSUE TITLE
Problems with 4.7.3

### ISSUE THREAD

**Issue by kuopassa** [gocom/rah_sitemap#3]
This plugin doesn't work at all in 4.7.3. It's unable to generate/output XML. It's quite an important plugin, so please *gocom* or someone else, consider updating the code.

**Comment by gocom** [comment]
Just tested it, and I can't reproduce:

```
$ docker-compose up && docker exec -it php /bin/bash
$ composer require rah/rah_sitemap:*@dev
$ curl http://localhost/rah_sitemap.xml
> <?xml version="1.0" encoding="utf-8"?> ...
```

It works just fine. The container runs Textpattern 4.7.2, but it should work just the same in 4.7.3.

**Comment by kuopassa** [comment]
I've got a few sites with Textpattern **4.6.2** and **4.7.3** using rah_sitemap version 1.2, which then produce errors like:

[20-Apr-2019 11:27:32 Europe/Helsinki] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /textpattern/lib/txplib_misc.php(1782) : eval()'d code:99
Stack trace:
#0 /textpattern/lib/txplib_misc.php(1895): rah_sitemap('textpattern', '')
#1 /textpattern/publish.php(548): callback_event('textpattern')
#2 /index.php(105): textpattern()
#3 {main}
  thrown in /textpattern/lib/txplib_misc.php(1782) : eval()'d code on line 99

(The above error is from a Textpattern 4.6.2. Perhaps it has something to do with PHP version. It's 7.1.27.

**Comment by gocom** [comment]
1.2.0 is not the most recent release, and this issues has been fixed since then (the whole plugin has been re-written pretty much).
